### ISSUE TITLE
Not able to create transaction on behalf of the account as an owner with the `owner` role

### ISSUE THREAD

**Issue by tantommy** [liftedinit/many-framework#113]
**Describe the bug**
Accounts where feature `0` is not present while trying to create a transaction on behalf of the account via an owner that has the `owner` role gives an `"Unauthorized to do this operation."` error.

**To Reproduce**
1. Create an account without feature `0` with an owner that has role `owner`
2. fund the account with some MFX or other token
3. Using the owner with `owner` role, create a transaction on behalf of the account
4. Error message is returned

**Expected behavior**
We should be able to send transactions on behalf of the account as long as the sender has the `owner` role on the account.

**Comment by fmorency** [comment]
Trying to `send` on behalf of an account without feature `0` should fail with an `Unauthorized to do this operation.`. Feature `0` is what's allowing you to perform a `send`. Without this feature, an account cannot perform `send` operations.

I can make the error message clearer.

**Comment by fmorency** [comment]
However, I **think** one can still submit a multisig transaction containing a `Send`. It will fail only at execution which might not be ideal.

**Comment by fmorency** [comment]
I was able to reproduce this issue. PR #138 contains the fix.
