### ISSUE TITLE
Limit the size of memos and data

### ISSUE THREAD

**Issue by hansl** [liftedinit/many-framework#118]
In general, also we could just reject large messages.

A few kilobytes for memos and data fields would be enough though. 4kb of memo and data ought to be enough for now.

**Comment by fmorency** [comment]
@hansl what would be the max size for the whole envelope?

**Comment by hansl** [comment]
There's already a hard limit of 10MB for an envelope. I want to limit memo and data further. With recursive multisig transactions, this can still hit the hard limit.
