### ISSUE TITLE
status endpoint for attributes does not include features

### ISSUE THREAD

**Issue by tantommy** [liftedinit/many-framework#165]
**Describe the bug**

per spec https://github.com/many-protocol/specification/blob/main/attributes/network/9_account.adoc#features, the list of features should also be returned in addition to the attributes.
> The list of features is available through the attribute’s arguments returned by the server’s status endpoint.

**To Reproduce**
1. `./target/debug/many message --server  https://alberto.app/api status '{}'`
2. response is:
```
{
    0: 1,
    1: "AbciModule(many-ledger)",
    2: h'a5010103270481022006215820e42d455843e8a18f2ee34ad9b807afc45652613630758740230080a4a5068f3c',
    3: 10000_1(h'01449aff697241dd16ce1d4a0e1719e0f78decee699b5db6158a333c91'),
    4: [0, 1, 2, 4, 6, 8, 9, 1002_1],
    5: "0.1.0",
    7: 300_1,
}
```

**Expected behavior**
attribute `9`(account) in the response should also have features, for example.

**Comment by fmorency** [comment]
This issue is more complex than previously thought if we want to fix it properly. 

Features are not currently linked to modules, but they probably should since the modules drag them in.
