### ISSUE TITLE
calling `account.create` and `account.addFeatures` with empty features should Error

### ISSUE THREAD

**Issue by tantommy** [liftedinit/many-framework#169]
**Describe the bug**
Per spec https://github.com/many-protocol/specification/blob/main/attributes/network/cddl/9_account.cddl#L96 and https://github.com/many-protocol/specification/blob/main/attributes/network/cddl/9_account.cddl#L248, calling `account.create` and `account.addFeatures` should require at least one feature in the set.

**To Reproduce**
1. call `account.create` or `account.addFeatures` with an empty set of features.
2. observe that no error is returned 

**Expected behavior**
An error should be returned if an empty set of features is provided.

**Additional context**
probably need changes here https://github.com/liftedinit/many-framework/blob/main/src/many-ledger/src/module.rs#L49

**Comment by fmorency** [comment]
#172
