### ISSUE TITLE
roles from account.info API response is returning accounts with no roles

### ISSUE THREAD

**Issue by tantommy** [liftedinit/many-framework#182]
**Describe the bug**
The `account.info` API response for is returning accounts with no roles.

**To Reproduce**
1. create an account and have at least one participant with roles.
2. edit the account and remove all roles from one of the participants via `removeRoles`
3. call `account.info` for this account
4. observe that the response contains the participant address from above mapped to an empty list of roles.

**Expected behavior**
Addresses that have no roles should be excluded from the response.

**Comment by fmorency** [comment]
@tantommy, how exactly did you get an account with owner/participant with zero roles? Using `removeRoles`?

I don't see anything in the spec that prevents this? Why is it an issue, according to you?

**Comment by fmorency** [comment]
@Denommus can you sync with @tantommy on this one, please? Thanks!

**Comment by tantommy** [comment]
> @tantommy, how exactly did you get an account with owner/participant with zero roles? Using `removeRoles`?
> 
> I don't see anything in the spec that prevents this? Why is it an issue, according to you?

yes, calling `removeRoles` to remove all the roles from an address.  i'll update the steps.

**Comment by Denommus** [comment]
@fmorency @tantommy I think the main question is: does it make more sense to use `removeRoles` to remove a participant completely, or is it better to have a method like `removeParticipant` that's specifically focused on that, and keep the current behavior (so that the user can keep an empty participant where they can add a role to that participant later)

**Comment by Denommus** [comment]
A third option would be to have `removeParticipant` execute `removeRoles` for all the roles of that participant.

**Comment by fmorency** [comment]
> @fmorency @tantommy I think the main question is: does it make more sense to use `removeRoles` to remove a participant completely, or is it better to have a method like `removeParticipant` that's specifically focused on that, and keep the current behavior (so that the user can keep an empty participant where they can add a role to that participant later)

Not sure we want to do that. I can't think of a use case where this is useful. I think your PR is okay.

**Comment by Denommus** [comment]
Fixed with https://github.com/liftedinit/many-rs/pull/174
