### ISSUE TITLE
 Timestamp and first migration

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-framework#205]
Following genesis, we discovered reproducibility issues when replaying the transaction history on new nodes. At the moment of writing these lines, new nodes are not able to catch up properly and crash on block 9400.

- [x] Add a migration path on block 9400 so new nodes can catch up
      **This will allow nodes to catch up BUT creating new problematic transactions is still possible**.
- [x] Remove `SystemTime::now()` and centralize time-related code in a `Timestamp` structure
- [x] Use the block timestamp in transactions

Following discussions with @hansl, we should
1. Restart from RC2 and implement the migration path on block 9400 so new nodes can catch up
2. Create a new release with the catch-up fix. **The behavior will still be broken but nodes should be able to catch up.**
3. Implement tasks 2 and 3 to correct the behavior
4. Create a new release and perform the migration on a future block

**Comment by fmorency** [comment]
Branch https://github.com/fmorency/many-framework/tree/fmorency/bug-205-catch-up was started from RC2 and includes everything up to `origin/main` cff0cf1f614a5b51918136e05d9f1c7d96e79c30, **EXCEPT**

> In ABCI we need to validate message timestamps w.r.t block time (#184) : 7c4abcd5074aaf009ab3a388d0ddffd0e52f7ce2
> Disable timestamp check in ledger when used as ABCI (#193)  : 8462f5fd02645e690aa7c32eaabed642e232ec18
> Allow override of tendermint version in make (#196) : 478989ee442e37f9c04388df50f8c09084e78d8b
> Update many-rs and remove dead code (#194) : b9ad92800241884995fcefe90ee9ce47b4a06a89
> Update many-rs to Timestamp and fix use of SystemTime (#200) : a8804085bcc28b75ac8333622f217e0da13bc577
> Remove duplicate linkage of ciborium (#204) : cff0cf1f614a5b51918136e05d9f1c7d96e79c30


I will work from this branch and fix the catch up issue first.

**Comment by fmorency** [comment]
I'm using `many-rs` commit 82e9dceda0310f11e0dec4892b04836edbcf56b1. It includes commit 72b978ff9464207b5517dbe2fb3b01b5b56855ff which we need to be able to disable the timestamp check in ledger.

**Comment by fmorency** [comment]
I created
1. A small tool to be able to dump RocksDB hex entries in a human-readable text, using `cbor-diag` & `many id`. This is for developers/debugging purposes only.
2. A script to bootstrap and manage a small MANY cluster locally without the use of docker. Makes dev/debugging more efficient until we refactor the Docker stuff.

**Comment by fmorency** [comment]
My test network has a single multisig transaction that was executed automatically.

So far, I tested
- Detecting the faulty transaction by its ID and applying the right timestamp in the `log_event()` function, all using many structures.
  - Found the issue https://github.com/liftedinit/many-rs/issues/176 while doing this
- Detecting the faulty transaction by its ID and applying the right timestamp in the `log_event()` function, all using CBOR.
- Change the faulty transaction to the right one before committing the results to the DB using a migration function based on the block height.
- Resetting the bad node with unsafe-reset-all.
- Using TM 0.35.9
- Contacting TM devs on Discord. 
  - Thread in https://discord.com/channels/669268347736686612/699634178173698108/1004042337980252246
- Verified the block info. Everything seems fine.
- Incorporated the latest Timestamp fix/block fix from RC6

No amount of fix allows the node to catch up. I always end up with

```
ERROR: failed to create node: error="error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 8CC91A664027126C40EF7FCB5B6EB2FB75C1B9AEA1F94DEFFA18EDA956509561, got F3353235AE0D52C7A422E4E73CC863BE0FD291457D741EFA36174FF36A242EF2" closerError=""
```

I verified that the AppHash is the right one after the migration to the correct transaction. I verified the transaction in the bad node database and it's the correct one after the migration.

The hex diff between the databases of a good and a bad node still has some differences after the migration, but the same human-readable file is generated by my scanner on both instances. Maybe something Merk-related?

Something else is going on here...

**Comment by fmorency** [comment]
Tendermint officially yanked all Tendermint 0.35.x.

See https://medium.com/the-interchain-foundation/discontinuing-tendermint-v0-35-a-postmortem-on-the-new-networking-layer-3696c811dabc

**Comment by hansl** [comment]
The latest nodes have caught up. This issue is now closed completely. What remains should be made into separate issues (e.g. how to mitigate in the future).
