### ISSUE TITLE
merk library error on cargo build

### ISSUE THREAD

**Issue by mjsorribas** [liftedinit/many-framework#248]
**cargo build error**
Operative System Mac OS Catalina 10.15.7
Library error : merk 
Cargo version tested : 1.64.0 (387270bc7 2022-09-16 and  1.62.0 (a748cf5a3 2022-06-08) 
**To Reproduce**
1. run cargo build
2. See error
`   Compiling merk v1.0.0 (https://github.com/liftedinit/merk.git?rev=da0b660abbfd58abd4a942773f205d2c079f3b27#da0b660a)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> .cargo/git/checkouts/merk-70d143d12d44ef86/da0b660/src/lib.rs:1:1
1 | #![feature(map_first_last)]
2 | #![feature(trivial_bounds)]
For more information about this error, try `rustc --explain E0554`.
error: could not compile `merk` due to 3 previous errors
warning: build failed, waiting for other jobs to finish..`

**Expected behavior**
clean build without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/1266065/193074387-3d26afef-59eb-400a-abbc-6ae3b5f3cf22.png)

**Comment by hansl** [comment]
You seem to have an override of the `merk` in your global config? That SHA is wrong: `merk-70d143d12d44ef86`. This is not a SHA on our repo.

**Comment by mjsorribas** [comment]
I used cargo 1.62.0 (a748cf5a3 2022-06-08) and I tried also with cargo 1.64.0 (387270bc7 2022-09-16)

**Comment by fmorency** [comment]
@mjsorribas Like @hansl said you seem to be trying to build the project using rust stable. Please use rust nightly.

You could try running `cargo +nightly build`, although cargo should be able to pick up which version to use from the `rust-toolchain.toml` file located in the root of the repo.

Simply run `rustup install nightly` if using `rustup` to manage your rust toolchains.
