### ISSUE TITLE
Implement KV-Store on ledger to allow storage of the credential IDs for WebAuthn

### ISSUE THREAD

**Issue by hansl** [liftedinit/many-framework#74]
There should be some simple ACL to ensure keys are not overwritten. Also, keys just need to be written once and never updated.

**Comment by hansl** [comment]
This will be a follow-up task after the-lifted-initiative/many-rs#68 is merged. Design will be documented.

**Comment by fmorency** [comment]
Linked to https://github.com/many-protocol/specification/issues/25 and https://github.com/many-protocol/specification/pull/27

**Comment by hansl** [comment]
Specification done this week, many-rs too.
